
[Definition]
actionstart =
actionstop =
actioncheck =
actionban = iptables -I fail2ban-sshd -s <ip> -j DROP 2>/dev/null || iptables -I INPUT -s <ip> -j DROP
            logger -p auth.warning -t sudo "fail2ban.actions [sshd] Ban <ip>"
actionunban = iptables -D fail2ban-sshd -s <ip> -j DROP 2>/dev/null || iptables -D INPUT -s <ip> -j DROP
              logger -p auth.warning -t sudo "fail2ban.actions [sshd] Unban <ip>"

[Init]
name = default
